version: 1.4.0
port: 7054
debug: false

tls:
  enabled: false
  certfile:
  keyfile:

ca:
  name: ca-issuer
  keyfile: /etc/hyperledger/fabric-ca-server/ca-key.pem
  certfile: /etc/hyperledger/fabric-ca-server/ca-cert.pem
  chainfile: /etc/hyperledger/fabric-ca-server/chain-cert.pem

crlsizelimit: 512000

db:
  type: sqlite3
  datasource: /etc/hyperledger/fabric-ca-server/fabric-ca-server.db
  tls:
    enabled: false
    certfiles:
    client:
      certfile:
      keyfile:

ldap:
  enabled: false
  url: ldap://cn=admin,dc=example,dc=org:admin@localhost:389/dc=example,dc=org
  tls:
    enabled: false
    certfiles:
    client:
      certfile:
      keyfile:

affiliations:
  issuer:
    - department1
    - department2
  investor:
    - department1
  regulator:
    - department1
  marketmaker:
    - department1
  custodian:
    - department1

registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.Attributes: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.DelegateRoles: "*"
        hf.Registrar.DelegateAttributes: "*"

bccsp:
  default: SW
  sw:
    hash: SHA2
    security: 256
    filekeystore:
      keystore: msp/keystore

cors:
  enabled: false
  origins:
    - "*"

csr:
  cn: ca.issuer.bondbridge.com
  keyrequest:
    algo: ecdsa
    size: 256
  names:
    - C: US
      ST: "North Carolina"
      L:
      O: Hyperledger
      OU: Fabric
  hosts:
    - ca.issuer.bondbridge.com
    - localhost
  ca:
    pathlen: 0
    pathlenzero: true
    expiry: 1314000h

idemix:
  rhpoolsize: 1000
  nonceexpiration: 15s
  noncesweepinterval: 15m

cfg:
  identities:
    passwordattempts: 10
  affiliations:
    cacheenabled: true
    cachesize: 100

